/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAllotmentRouteImport } from './routes/_authenticated/allotment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKitchenSheetRouteImport } from './routes/_authenticated/kitchen-sheet'
import { Route as AuthenticatedOrderImportRouteImport } from './routes/_authenticated/order-import'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPackingRouteImport } from './routes/_authenticated/packing'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedRequirementsRouteImport } from './routes/_authenticated/requirements'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedReturnsDashboardRouteImport } from './routes/_authenticated/returns-dashboard'
import { Route as AuthenticatedSnacksRouteImport } from './routes/_authenticated/snacks'
import { Route as AuthenticatedSnacksReportRouteImport } from './routes/_authenticated/snacks_.report'
import { Route as AuthenticatedSnacksRestockRouteImport } from './routes/_authenticated/snacks_.restock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAllotmentRoute = AuthenticatedAllotmentRouteImport.update({
  id: '/allotment',
  path: '/allotment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitchenSheetRoute =
  AuthenticatedKitchenSheetRouteImport.update({
    id: '/kitchen-sheet',
    path: '/kitchen-sheet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderImportRoute =
  AuthenticatedOrderImportRouteImport.update({
    id: '/order-import',
    path: '/order-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackingRoute = AuthenticatedPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequirementsRoute =
  AuthenticatedRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsDashboardRoute =
  AuthenticatedReturnsDashboardRouteImport.update({
    id: '/returns-dashboard',
    path: '/returns-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSnacksRoute = AuthenticatedSnacksRouteImport.update({
  id: '/snacks',
  path: '/snacks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSnacksReportRoute =
  AuthenticatedSnacksReportRouteImport.update({
    id: '/snacks_/report',
    path: '/snacks/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSnacksRestockRoute =
  AuthenticatedSnacksRestockRouteImport.update({
    id: '/snacks_/restock',
    path: '/snacks/restock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/allotment': typeof AuthenticatedAllotmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kitchen-sheet': typeof AuthenticatedKitchenSheetRoute
  '/order-import': typeof AuthenticatedOrderImportRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/packing': typeof AuthenticatedPackingRoute
  '/production': typeof AuthenticatedProductionRoute
  '/requirements': typeof AuthenticatedRequirementsRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/returns-dashboard': typeof AuthenticatedReturnsDashboardRoute
  '/snacks': typeof AuthenticatedSnacksRoute
  '/snacks/report': typeof AuthenticatedSnacksReportRoute
  '/snacks/restock': typeof AuthenticatedSnacksRestockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/allotment': typeof AuthenticatedAllotmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kitchen-sheet': typeof AuthenticatedKitchenSheetRoute
  '/order-import': typeof AuthenticatedOrderImportRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/packing': typeof AuthenticatedPackingRoute
  '/production': typeof AuthenticatedProductionRoute
  '/requirements': typeof AuthenticatedRequirementsRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/returns-dashboard': typeof AuthenticatedReturnsDashboardRoute
  '/snacks': typeof AuthenticatedSnacksRoute
  '/snacks/report': typeof AuthenticatedSnacksReportRoute
  '/snacks/restock': typeof AuthenticatedSnacksRestockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/allotment': typeof AuthenticatedAllotmentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kitchen-sheet': typeof AuthenticatedKitchenSheetRoute
  '/_authenticated/order-import': typeof AuthenticatedOrderImportRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/packing': typeof AuthenticatedPackingRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/requirements': typeof AuthenticatedRequirementsRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/returns-dashboard': typeof AuthenticatedReturnsDashboardRoute
  '/_authenticated/snacks': typeof AuthenticatedSnacksRoute
  '/_authenticated/snacks_/report': typeof AuthenticatedSnacksReportRoute
  '/_authenticated/snacks_/restock': typeof AuthenticatedSnacksRestockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/allotment'
    | '/dashboard'
    | '/kitchen-sheet'
    | '/order-import'
    | '/orders'
    | '/packing'
    | '/production'
    | '/requirements'
    | '/returns'
    | '/returns-dashboard'
    | '/snacks'
    | '/snacks/report'
    | '/snacks/restock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/allotment'
    | '/dashboard'
    | '/kitchen-sheet'
    | '/order-import'
    | '/orders'
    | '/packing'
    | '/production'
    | '/requirements'
    | '/returns'
    | '/returns-dashboard'
    | '/snacks'
    | '/snacks/report'
    | '/snacks/restock'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/allotment'
    | '/_authenticated/dashboard'
    | '/_authenticated/kitchen-sheet'
    | '/_authenticated/order-import'
    | '/_authenticated/orders'
    | '/_authenticated/packing'
    | '/_authenticated/production'
    | '/_authenticated/requirements'
    | '/_authenticated/returns'
    | '/_authenticated/returns-dashboard'
    | '/_authenticated/snacks'
    | '/_authenticated/snacks_/report'
    | '/_authenticated/snacks_/restock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/allotment': {
      id: '/_authenticated/allotment'
      path: '/allotment'
      fullPath: '/allotment'
      preLoaderRoute: typeof AuthenticatedAllotmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitchen-sheet': {
      id: '/_authenticated/kitchen-sheet'
      path: '/kitchen-sheet'
      fullPath: '/kitchen-sheet'
      preLoaderRoute: typeof AuthenticatedKitchenSheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order-import': {
      id: '/_authenticated/order-import'
      path: '/order-import'
      fullPath: '/order-import'
      preLoaderRoute: typeof AuthenticatedOrderImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packing': {
      id: '/_authenticated/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof AuthenticatedPackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requirements': {
      id: '/_authenticated/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof AuthenticatedRequirementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns-dashboard': {
      id: '/_authenticated/returns-dashboard'
      path: '/returns-dashboard'
      fullPath: '/returns-dashboard'
      preLoaderRoute: typeof AuthenticatedReturnsDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/snacks': {
      id: '/_authenticated/snacks'
      path: '/snacks'
      fullPath: '/snacks'
      preLoaderRoute: typeof AuthenticatedSnacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/snacks_/report': {
      id: '/_authenticated/snacks_/report'
      path: '/snacks/report'
      fullPath: '/snacks/report'
      preLoaderRoute: typeof AuthenticatedSnacksReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/snacks_/restock': {
      id: '/_authenticated/snacks_/restock'
      path: '/snacks/restock'
      fullPath: '/snacks/restock'
      preLoaderRoute: typeof AuthenticatedSnacksRestockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAllotmentRoute: typeof AuthenticatedAllotmentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKitchenSheetRoute: typeof AuthenticatedKitchenSheetRoute
  AuthenticatedOrderImportRoute: typeof AuthenticatedOrderImportRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPackingRoute: typeof AuthenticatedPackingRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedRequirementsRoute: typeof AuthenticatedRequirementsRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedReturnsDashboardRoute: typeof AuthenticatedReturnsDashboardRoute
  AuthenticatedSnacksRoute: typeof AuthenticatedSnacksRoute
  AuthenticatedSnacksReportRoute: typeof AuthenticatedSnacksReportRoute
  AuthenticatedSnacksRestockRoute: typeof AuthenticatedSnacksRestockRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAllotmentRoute: AuthenticatedAllotmentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKitchenSheetRoute: AuthenticatedKitchenSheetRoute,
  AuthenticatedOrderImportRoute: AuthenticatedOrderImportRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPackingRoute: AuthenticatedPackingRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedRequirementsRoute: AuthenticatedRequirementsRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedReturnsDashboardRoute: AuthenticatedReturnsDashboardRoute,
  AuthenticatedSnacksRoute: AuthenticatedSnacksRoute,
  AuthenticatedSnacksReportRoute: AuthenticatedSnacksReportRoute,
  AuthenticatedSnacksRestockRoute: AuthenticatedSnacksRestockRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
